USE DETAILS;

CREATE TABLE USER_INFO(
	USER_NAME VARCHAR(50) NOT NULL,
	USER_PHNO INT NOT NULL UNIQUE,
	USER_EMAIL VARCHAR(250) UNIQUE,
	ADDRESS VARCHAR(500) NOT NULL,
	AGE INT NOT NULL CHECK (AGE>18),
	STATE VARCHAR(100) NOT NULL,
	COUNTRY VARCHAR(200) default 'INDIA',
	AADHAR_NUMBER BIGINT NOT NULL UNIQUE,
	USER_ID INT auto_increment PRIMARY KEY
);
DROP TABLE USER_INFO;
truncate table user_info;

SELECT * FROM USER_INFO;
ALTER TABLE USER_INFO CHANGE USER_PHNO USER_PHNO BIGINT NOT NULL UNIQUE;

INSERT INTO USER_INFO (USER_NAME, USER_PHNO, USER_EMAIL, ADDRESS, AGE, STATE, AADHAR_NUMBER) VALUES 
					('BHOOMIKA', 9008765432, 'BHOOMI@GMAIL.COM', 'MYSORE', 19, 'KARNATAKA', '989065554323'),
					('NAYANA', 7306775432, 'NAYANA@GMAIL.COM', 'BANGALORE', 25, 'KARNATAKA', '967890554323'),
                    ('ARJIN', 734635432, 'ARJUN@GMAIL.COM', 'BANGALORE', 25, 'KARNATAKA', '909088554323');

INSERT INTO USER_INFO (USER_NAME, USER_PHNO, USER_EMAIL, ADDRESS, AGE, STATE, AADHAR_NUMBER) VALUES 
					('KAVANA', 1234567899, 'KAVANA@GMAIL.COM', 'Coimbatore', 29, 'Tamil Nadu', '123412341234'),
					('RAMESH', 2345678901, 'RAMESH@GMAIL.COM', 'Coimbatore', 35, 'Tamil Nadu', '234523452345'),
                    ('SUBRMANYA', 3456789012, 'SUBRMANYA@GMAIL.COM', 'Coimbatore', 28, 'Tamil Nadu', '123456781234');

SELECT * FROM USER_INFO HAVING STATE = "Tamil Nadu";
SELECT STATE FROM USER_INFO GROUP BY STATE;
SELECT STATE, COUNT(STATE)FROM USER_INFO GROUP BY STATE;

SELECT STATE, COUNT(STATE)FROM USER_INFO GROUP BY STATE HAVING STATE = 'KARNATAKA';
	-- SELECT AGE, COUNT(AGE)FROM USER_INFO GROUP BY AGE HAVING AGE <= 25;

-- SELECT STATE,USER_NAME, COUNT(*)
-- 	FROM USER_INFO 
--     GROUP BY STATE HAVING USER_NAME="" AND STATE="";
--     
-- SET GLOBAL sql_mode=(SELECT REPLACE(@@sql_mode,'ONLY_FULL_GROUP_BY',''));
