-- CREATE DATABASE RELATION_DB;
USE RELATION_DB;

CREATE TABLE APP_DETAILS(
	APP_ID INT AUTO_INCREMENT PRIMARY KEY,
    APP_NAME VARCHAR(20) NOT NULL UNIQUE,
    APP_VER VARCHAR(20) NOT NULL,
    NO_OF_USERS INT DEFAULT 0
    );
-- DROP TABLE APP_DETAILS;
SELECT * FROM APP_DETAILS;
INSERT INTO APP_DETAILS (APP_NAME,APP_VER,NO_OF_USERS) VALUES
	("WHATSAPP","V21.9.1",180),
    ("INSTAGRAM","V18.0.1",120),
    ("HOTSTART","V3.8",180),
    ("LINKEDIN","V5.2.0",80),
    ("GOOGLE","V10.7.3",300);
-- TRUNCATE TABLE APP_DETAILS; 
CREATE TABLE USER_DETAILS( 
	USER_ID INT AUTO_INCREMENT PRIMARY KEY,
    USER_NAME VARCHAR(20) NOT NULL,
    USER_EMAIL VARCHAR(100) NOT NULL UNIQUE,
    APP_ID INT,
    -- FOREIGN KEY (COL_NAME) REF PARENT_TABLE(COL_NAME)
    FOREIGN KEY (APP_ID) REFERENCES APP_DETAILS(APP_ID) ON DELETE SET NULL
    );
 SELECT * FROM USER_DETAILS;
 -- DROP TABLE USER_DETAILS;
 INSERT INTO USER_DETAILS (USER_NAME,USER_EMAIL,APP_ID) VALUES
	 ("ANUSHA","anusha@gmail.com",4),
	 ("ANISH","anisha@gmail.com",2),
	 ("BHOOMIKA","bhoomi@gmail.com",1);
-- TRUNCATE TABLE USER_DETAILS; 

SELECT * FROM USER_DETAILS AS U, APP_DETAILS AS A 
WHERE U.USER_NAME = "BHOOMIKA" AND U.APP_ID = A.APP_ID;

-- GET AVG OF USERS
-- GET SUM OF ALL USERS
-- MAX OF ALL USERS
-- MIN OF ALL USERS
-- TOTAL COUNT OF ALL THE DEATAILS

SELECT avg(NO_OF_USERS) AS AVG_USERS FROM APP_DETAILS;
SELECT SUM(NO_OF_USERS) AS SUM_OF_USERS FROM  APP_DETAILS;
SELECT MAX(NO_OF_USERS) AS SUM_OF_USERS FROM  APP_DETAILS;
SELECT MIN(NO_OF_USERS) AS SUM_OF_USERS FROM  APP_DETAILS;
SELECT COUNT(*) AS TOTAL_USERS FROM  USER_DETAILS;