CREATE DATABASE DETAILS;
DROP DATABASE DETAILS;

CREATE SCHEMA DETAILS;
-- DROP SCHEMA DETAILS;

USE DETAILS;

CREATE TABLE APPLICATION_DETAILS(
	APP_ID INT,
    APP_NAME VARCHAR(100),
    APP_VERSION VARCHAR(100),
    APP_RELEASE_DATE DATE,
    APP_RELEASE_YEAR YEAR,
    NUMBER_OF_USEAR INT );

RENAME TABLE APPLICATION_DETAILS TO APP_NAME;
-- DROP TABLE APP_NAME;
RENAME TABLE APP_NAME TO APPLICATION_DETAILS;

ALTER TABLE APPLICATION_DETAILS ADD COLUMN SIZE VARCHAR(50);

ALTER TABLE APPLICATION_DETAILS DROP COLUMN SIZE;

SELECT * FROM APPLICATION_DETAILS;

INSERT INTO APPLICATION_DETAILS VALUES(12,"INSTAGRAM","V2.0","2000-01-20",2000,40,"49MB");
INSERT INTO APPLICATION_DETAILS VALUES(12,"INSTAGRAM","V2.0","2000-01-20",2000,40,"49MB");

UPDATE APPLICATION_DETAILS SET APP_NAME = "INSTAGRAM_LIGHT"; -- ERR "Error Code: 1175. You are using safe update mode and you tried to update a table without a WHERE that uses a KEY column.  To disable safe mode, toggle the option in Preferences -> SQL Editor and reconnect."
	-- TO TURN OFF SAFE UPDATE ASIGN ZERO
SET SQL_SAFE_UPDATES = 0; 
	-- TO DELETE DATA & KEEPING TABLE COLUMN -> TRUNCATE
TRUNCATE APPLICATION_DETAILS;
	-- DELETE TABLE
DROP TABLE APPLICATION_DETAILS;

CREATE TABLE APPLICATION_DETAILS(
	APP_ID INT UNIQUE NOT NULL,
    APP_NAME VARCHAR(25) UNIQUE NOT NULL,
    APP_VER VARCHAR(20) NOT NULL,
    APP_RELEASE_DATE DATE NOT NULL,
    APP_RELEASE_YEAR INT NOT NULL,
    NUMBER_OF_USERS INT,
    APP_SIZE VARCHAR(20) NOT NULL
    );
 
INSERT INTO APPLICATION_DETAILS VALUES(101,"SNAPCHAT","V3.1.2","2012-08-12",2012,234,"32MB");
INSERT INTO APPLICATION_DETAILS VALUES(102,"INSTAGRAM","V2.0","2000-01-10",2000,2100,"29MB");
INSERT INTO APPLICATION_DETAILS VALUES(103,"WHATSAPP","V8.6.1","2005-08-01",2005,89234,"20MB");
INSERT INTO APPLICATION_DETAILS VALUES(104,"FACEBOOK","V10.8","2003-05-16",2003,12834,"26MB");

SELECT * FROM APPLICATION_DETAILS;

SELECT * FROM APPLICATION_DETAILS WHERE APP_NAME = "WHATSAPP";
SELECT * FROM APPLICATION_DETAILS WHERE APP_ID = 102;
	-- TO GET NO. OF RECORD = 4
SELECT COUNT(*) FROM APPLICATION_DETAILS;
	-- TO GIVE ALIAS NAME [TO DISPALY COUNT RATHER THAN COUNT(*)]
SELECT COUNT(*) AS COUNT FROM APPLICATION_DETAILS;
	-- TO ADD NUMBER OF USERS FROM ALL APP
SELECT SUM(NUMBER_OF_USERS) AS TOTAL_USERS FROM APPLICATION_DETAILS;
		
	-- INSERT ANOTHER DATA WITH APP_NAME TO  NULL
INSERT INTO APPLICATION_DETAILS VALUES(109,NULL,"V14.0","2008-09-09",2008,40,"40MB"); -- Error Code: 1048. Column 'APP_NAME' cannot be null
	
    -- RELATIONAL OP
SELECT * FROM APPLICATION_DETAILS WHERE APP_ID > 102;
SELECT * FROM APPLICATION_DETAILS WHERE APP_ID < 103;
SELECT * FROM APPLICATION_DETAILS WHERE APP_ID <= 103;
SELECT * FROM APPLICATION_DETAILS WHERE APP_ID >= 103;
SELECT * FROM APPLICATION_DETAILS WHERE APP_ID = 104;
SELECT * FROM APPLICATION_DETAILS WHERE APP_ID != 101;

	-- lOGICAL OPERATORS: AND,OR
SELECT * FROM APPLICATION_DETAILS WHERE APP_SIZE > "20MB" OR APP_ID = 102;
SELECT * FROM APPLICATION_DETAILS WHERE APP_SIZE >="20MB" AND APP_ID = 102;
	-- RELATIONAL OP: NOT IN , BETWEEN
SELECT * FROM APPLICATION_DETAILS WHERE APP_VER NOT IN ("V2.0","V10.8")  ;
SELECT * FROM APPLICATION_DETAILS WHERE NUMBER_OF_USERS BETWEEN 100 AND 10000;

 -- TASK: DISPLAY APP_NAME INSTAGRAM AND APP_SIZE 20MB
SELECT * FROM APPLICATION_DETAILS WHERE APP_NAME = "INSTAGRAM" AND APP_SIZE = "20MB";

