USE DAY3;
CREATE VIEW VIEW_NAME AS
	SELECT C_NAME, C_PHNO FROM CUSTOMERS;
SELECT * FROM view_name;
    
CREATE TABLE t (qty INT, price INT);
INSERT INTO t VALUES(3, 50);
CREATE VIEW v AS SELECT qty, price, qty*price AS value FROM t;
SELECT * FROM v;
